# 💰 Funding Configuration for BailBondPro
# These are supported funding model platforms

# GitHub Sponsors
github: [kalivibecoding]

# Patreon
patreon: bailbondpro

# Open Collective
open_collective: bailbondpro

# Ko-fi
ko_fi: bailbondpro

# Tidelift
tidelift: npm/bailbondpro

# Community Bridge
community_bridge: bailbondpro

# Liberapay
liberapay: bailbondpro

# IssueHunt
issuehunt: kalivibecoding

# Buy Me a Coffee
custom: ['https://www.buymeacoffee.com/bailbondpro', 'https://paypal.me/bailbondpro']