name: 🐛 Bug Report
description: Report a bug or unexpected behavior in BailBondPro
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below with as much detail as possible.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have read the documentation and troubleshooting guide
          required: true
        - label: I can reproduce this bug consistently
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System unusable, data loss)
        - High (Major functionality broken)
        - Medium (Minor functionality affected)
        - Low (Cosmetic or minor inconvenience)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Authentication
        - Dashboard
        - Client Management
        - Bond Processing
        - Payment Processing
        - Reporting
        - API
        - Database
        - UI/UX
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of BailBondPro are you using?
      placeholder: e.g., v1.2.3 or commit hash
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where did this bug occur?
      options:
        - Production
        - Staging
        - Development
        - Local
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Mobile Safari
        - Mobile Chrome
        - Other
    validations:
      required: false

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of the browser?
      placeholder: e.g., Chrome 119.0.6045.105
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - Windows 11
        - Windows 10
        - macOS Sonoma
        - macOS Ventura
        - macOS Monterey
        - Ubuntu 22.04
        - Ubuntu 20.04
        - iOS
        - Android
        - Other
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any relevant error messages or logs
      placeholder: Paste error logs here...
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
      placeholder: Drag and drop screenshots here or paste image URLs...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context about the problem here...
    validations:
      required: false

  - type: checkboxes
    id: impact
    attributes:
      label: Impact Assessment
      description: How does this bug affect your work?
      options:
        - label: Blocks critical business operations
        - label: Affects daily workflow
        - label: Minor inconvenience
        - label: Cosmetic issue only

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Have you found any temporary workaround?
      placeholder: Describe any workaround you've found...
    validations:
      required: false